language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    
sudo: false

cache:
    directories:
        - $HOME/.composer/cache

env:
  - SYMFONY_VERSION=2.5.*

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
    - php: hhvm
  include:
    - php: 5.4.0
      env: SYMFONY_VERSION=2.3.* COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.6.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
  allow_failures:
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*

before_script:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer update --prefer-dist $COMPOSER_FLAGS
  - vendor/symfony-cmf/testing/bin/travis/phpcr_odm_doctrine_dbal.sh

script:
    - phpunit --coverage-text
    - ./vendor/symfony-cmf/testing/bin/server &
    - ./vendor/bin/behat

notifications:
  irc: "irc.freenode.org#symfony-cmf"
